### ISSUE TITLE
Is incremental parsing supported?

### ISSUE THREAD

**Issue by Superice666** [zhong-j-yu/rekex#9]
First of all, thanks for your amazing work! @zhong-j-yu 
I'm developinng a DSL these days and I've already made an ugly parser. Each change on the grammar of my DSL takes me a lot of time because of its bad design. So I'm considering using rekex instead. The design of relex actually amazed me. Using parameter annotations on record parameters is a genius idea! 
But there is still one thing that worries me. That's the incremental parsing because I want to use one parser in both compilers and IDEs. I have no time for maintaining more than one parsers. Could you pls tell me if incremental parsing is supported? If not, is there any simple way to fix it? Thank you!

**Comment by zhong-j-yu** [comment]
Thank you for considering Rekex. I'm afraid I've never thought about incremental parsing, which is a whole new dimension of complexity. The Rekex model maps a valid input to a well-typed syntax tree; if the input contains local syntax errors (when it's being edited in IDE), Rekex can't produce a tree with nodes that represent non-grammatic parts of the input. Also, Rekex produces a tree that is statically-typed with immutable datanodes, it's difficult to incrementally update parts of the tree. I'm sorry Rekex may not be helpful for your needs :(

**Comment by Superice666** [comment]
It's pity. But I'll still keep an eye on rekex. Thank you!

**Comment by zhong-j-yu** [comment]
Thank you too. I hope the general design idea of Rekex could be of some use to you.
